const COMPOSE_VIEW_STRING = 'compose';
const LIVE_VIEW_STRING = 'live';
const ITEMS_COLLECTION_NAME = 'items';
const LIVE_VIEW_ACTIONS_COLLECTION_NAME = 'appactions';
const COMPOSE_VIEW_ACTIONS_COLLECTION_NAME = 'actions';
const USERS_COLLECTION_NAME = 'users';
const APP_INSTANCES_COLLECTION_NAME = 'appinstances';
const APP_INSTANCE_RESOURCES_COLLECTION_NAME = 'appinstanceresources';
const TASKS_COLLECTION_NAME = 'tasks';
const LOCAL_CONTEXTUAL_STRING = 'local-contextual';
const LIGHT_USER_STRING = 'light';
const GRAASP_USER_STRING = 'graasp';

module.exports = {
  COMPOSE_VIEW_STRING,
  LIVE_VIEW_STRING,
  ITEMS_COLLECTION_NAME,
  LIVE_VIEW_ACTIONS_COLLECTION_NAME,
  COMPOSE_VIEW_ACTIONS_COLLECTION_NAME,
  USERS_COLLECTION_NAME,
  APP_INSTANCES_COLLECTION_NAME,
  APP_INSTANCE_RESOURCES_COLLECTION_NAME,
  TASKS_COLLECTION_NAME,
  LOCAL_CONTEXTUAL_STRING,
  LIGHT_USER_STRING,
  GRAASP_USER_STRING,
};
